version: '3'

services:
  mysql:
    image: mysql:5.7.19
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=peixeurbano
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
  
volumes:
  mysql_data:
  