server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/peixeurbano
    username: admin
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:mysql://localhost:3306/peixeurbano
    user: admin
    password: password
    locations: classpath:/db/migration
    outOfOrder: true
